### ISSUE TITLE
Weird documentation structure - documentation for readers

### ISSUE THREAD

**Issue by creat89** [crossminer/scava-docs#14]
Hello,

Today I was looking for the documentation regarding the readers, found in https://github.com/crossminer/scava-docs/blob/master/docs/others/resources/readers/index.md . However, it is impossible to access this document from https://crossminer.github.io/scava-docs/. And in https://scava-docs.readthedocs.io/en/latest/ we can access but not from the starting page, but scrolling down the left menu almost at the end.

Can anyone be happy to explain me what's happening?

**Comment by borisbaldassari** [comment]
Yeah, the page can be found at https://scava-docs.readthedocs.io/en/latest/others/resources/readers/
The last refactoring has been done by @aabherve and @davidediruscio I believe, they may have more answers on the structure.

**Comment by creat89** [comment]
I had updated the structure and put them in User Guide some months ago in commit https://github.com/crossminer/scava-docs/commit/f075cccf7b92afe638024c1682c1d9af915fc233
